[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dunk_ai"
version = "0.1.0"
description = "DUNK AI project"
authors = [
    { name = "Utkarsh" }
]

[tool.setuptools.packages.find]
where = ["."]